In [4]:
using CSV
using DataFrames
using DelimitedFiles
include("test.jl")


printRegression (generic function with 1 method)

In [78]:
df = CSV.read("test/dataset.csv")
#"name" diabaikan karena terlalu beragam
df = df[2:size(df,1), 2:size(df,2)]
df

┌ Warning: `CSV.read(input; kw...)` is deprecated in favor of `DataFrame!(CSV.File(input; kw...))`
└ @ CSV C:\Users\USER\.julia\packages\CSV\UWuB2\src\CSV.jl:40


4339×7 DataFrame. Omitted printing of 2 columns
│ Row  │ year  │ selling_price │ km_driven │ fuel   │ seller_type │
│      │ Int64 │ Int64         │ Int64     │ String │ String      │
├──────┼───────┼───────────────┼───────────┼────────┼─────────────┤
│ 1    │ 2007  │ 135000        │ 50000     │ Petrol │ Individual  │
│ 2    │ 2012  │ 600000        │ 100000    │ Diesel │ Individual  │
│ 3    │ 2017  │ 250000        │ 46000     │ Petrol │ Individual  │
│ 4    │ 2014  │ 450000        │ 141000    │ Diesel │ Individual  │
│ 5    │ 2007  │ 140000        │ 125000    │ Petrol │ Individual  │
│ 6    │ 2016  │ 550000        │ 25000     │ Petrol │ Individual  │
│ 7    │ 2014  │ 240000        │ 60000     │ Petrol │ Individual  │
│ 8    │ 2015  │ 850000        │ 25000     │ Petrol │ Individual  │
│ 9    │ 2017  │ 365000        │ 78000     │ CNG    │ Individual  │
│ 10   │ 2015  │ 260000        │ 35000     │ Petrol │ Individual  │
⋮
│ 4329 │ 2010  │ 160000        │ 60000     │ Petrol │ Individual  │
│ 4330 │ 2010  │ 150000        │ 130000    │ Diesel │ Individual  │
│ 4331 │ 2015  │ 530000        │ 175000    │ Diesel │ Individual  │
│ 4332 │ 2015  │ 750000        │ 120000    │ Diesel │ Individual  │
│ 4333 │ 2012  │ 225000        │ 90000     │ Diesel │ Individual  │
│ 4334 │ 2012  │ 600000        │ 170000    │ Diesel │ Individual  │
│ 4335 │ 2014  │ 409999        │ 80000     │ Diesel │ Individual  │
│ 4336 │ 2014  │ 409999        │ 80000     │ Diesel │ Individual  │
│ 4337 │ 2009  │ 110000        │ 83000     │ Petrol │ Individual  │
│ 4338 │ 2016  │ 865000        │ 90000     │ Diesel │ Individual  │
│ 4339 │ 2016  │ 225000        │ 40000     │ Petrol │ Individual  │

In [31]:
#mengurutkan data sesuai harganya agar pengubahan kolom kategorikal ke numerik
#dapat menjadi lebih tepat
sorted = sort!(df, :selling_price)
sorted

4339×7 DataFrame. Omitted printing of 2 columns
│ Row  │ year  │ selling_price │ km_driven │ fuel   │ seller_type │
│      │ Int64 │ Int64         │ Int64     │ String │ String      │
├──────┼───────┼───────────────┼───────────┼────────┼─────────────┤
│ 1    │ 2005  │ 20000         │ 25000     │ Petrol │ Individual  │
│ 2    │ 2000  │ 22000         │ 42743     │ Petrol │ Dealer      │
│ 3    │ 2004  │ 30000         │ 60000     │ Petrol │ Individual  │
│ 4    │ 2002  │ 35000         │ 100000    │ Petrol │ Individual  │
│ 5    │ 2009  │ 35000         │ 50000     │ Petrol │ Individual  │
│ 6    │ 2012  │ 35000         │ 35000     │ Petrol │ Individual  │
│ 7    │ 2004  │ 37500         │ 90000     │ Petrol │ Individual  │
│ 8    │ 1998  │ 40000         │ 40000     │ Petrol │ Individual  │
│ 9    │ 1998  │ 40000         │ 40000     │ Petrol │ Individual  │
│ 10   │ 2001  │ 40000         │ 30000     │ Petrol │ Individual  │
⋮
│ 4329 │ 2019  │ 4950000       │ 30000     │ Diesel │ Dealer      │
│ 4330 │ 2019  │ 4950000       │ 30000     │ Diesel │ Dealer      │
│ 4331 │ 2019  │ 4950000       │ 30000     │ Diesel │ Dealer      │
│ 4332 │ 2019  │ 4950000       │ 30000     │ Diesel │ Dealer      │
│ 4333 │ 2019  │ 4950000       │ 30000     │ Diesel │ Dealer      │
│ 4334 │ 2019  │ 4950000       │ 30000     │ Diesel │ Dealer      │
│ 4335 │ 2019  │ 4950000       │ 30000     │ Diesel │ Dealer      │
│ 4336 │ 2019  │ 4950000       │ 30000     │ Diesel │ Dealer      │
│ 4337 │ 2016  │ 5500000       │ 77350     │ Diesel │ Dealer      │
│ 4338 │ 2017  │ 8150000       │ 6500      │ Diesel │ Dealer      │
│ 4339 │ 2016  │ 8900000       │ 13000     │ Petrol │ Dealer      │

In [35]:
#Mengambil data train
train = sorted[1:100, :]


100×7 DataFrame. Omitted printing of 2 columns
│ Row │ year  │ selling_price │ km_driven │ fuel   │ seller_type │
│     │ Int64 │ Int64         │ Int64     │ String │ String      │
├─────┼───────┼───────────────┼───────────┼────────┼─────────────┤
│ 1   │ 2005  │ 20000         │ 25000     │ Petrol │ Individual  │
│ 2   │ 2000  │ 22000         │ 42743     │ Petrol │ Dealer      │
│ 3   │ 2004  │ 30000         │ 60000     │ Petrol │ Individual  │
│ 4   │ 2002  │ 35000         │ 100000    │ Petrol │ Individual  │
│ 5   │ 2009  │ 35000         │ 50000     │ Petrol │ Individual  │
│ 6   │ 2012  │ 35000         │ 35000     │ Petrol │ Individual  │
│ 7   │ 2004  │ 37500         │ 90000     │ Petrol │ Individual  │
│ 8   │ 1998  │ 40000         │ 40000     │ Petrol │ Individual  │
│ 9   │ 1998  │ 40000         │ 40000     │ Petrol │ Individual  │
│ 10  │ 2001  │ 40000         │ 30000     │ Petrol │ Individual  │
⋮
│ 90  │ 2002  │ 65000         │ 100000    │ Petrol │ Individual  │
│ 91  │ 2005  │ 65000         │ 70000     │ Petrol │ Individual  │
│ 92  │ 2005  │ 65000         │ 70000     │ Petrol │ Individual  │
│ 93  │ 2005  │ 65000         │ 150000    │ Petrol │ Individual  │
│ 94  │ 2006  │ 65000         │ 124439    │ Petrol │ Individual  │
│ 95  │ 2008  │ 65000         │ 110000    │ Petrol │ Individual  │
│ 96  │ 2008  │ 65000         │ 140000    │ Petrol │ Individual  │
│ 97  │ 2011  │ 65000         │ 60000     │ Petrol │ Individual  │
│ 98  │ 2001  │ 68000         │ 70000     │ Petrol │ Individual  │
│ 99  │ 2001  │ 68000         │ 70000     │ Petrol │ Individual  │
│ 100 │ 2009  │ 68000         │ 120000    │ Petrol │ Individual  │

In [46]:
# Mengambil kolom "owner" dan mengubahnya menjadi numerik
owner = changeCatToNum(train[:,7])
for i=1:100
    train[i,7] = string(owner[i])
end

# Mengambil kolom "transmission" dan mengubahnya menjadi numerik
transmission = changeCatToNum(train[:,6])
for i=1:100
    train[i,6] = string(transmission[i])
end

# Mengambil kolom "seller_type" dan mengubahnya menjadi numerik
seller = changeCatToNum(train[:,5])
for i=1:100
    train[i,5] = string(seller[i])
end

# Mengambil kolom "fuel" dan mengubahnya menjadi numerik
fuel = changeCatToNum(train[:,4])
for i=1:100
    train[i,4] = string(fuel[i])
end

train

100×7 DataFrame. Omitted printing of 2 columns
│ Row │ year  │ selling_price │ km_driven │ fuel   │ seller_type │
│     │ Int64 │ Int64         │ Int64     │ String │ String      │
├─────┼───────┼───────────────┼───────────┼────────┼─────────────┤
│ 1   │ 2005  │ 20000         │ 25000     │ 1      │ 1           │
│ 2   │ 2000  │ 22000         │ 42743     │ 1      │ 2           │
│ 3   │ 2004  │ 30000         │ 60000     │ 1      │ 1           │
│ 4   │ 2002  │ 35000         │ 100000    │ 1      │ 1           │
│ 5   │ 2009  │ 35000         │ 50000     │ 1      │ 1           │
│ 6   │ 2012  │ 35000         │ 35000     │ 1      │ 1           │
│ 7   │ 2004  │ 37500         │ 90000     │ 1      │ 1           │
│ 8   │ 1998  │ 40000         │ 40000     │ 1      │ 1           │
│ 9   │ 1998  │ 40000         │ 40000     │ 1      │ 1           │
│ 10  │ 2001  │ 40000         │ 30000     │ 1      │ 1           │
⋮
│ 90  │ 2002  │ 65000         │ 100000    │ 1      │ 1           │
│ 91  │ 2005  │ 65000         │ 70000     │ 1      │ 1           │
│ 92  │ 2005  │ 65000         │ 70000     │ 1      │ 1           │
│ 93  │ 2005  │ 65000         │ 150000    │ 1      │ 1           │
│ 94  │ 2006  │ 65000         │ 124439    │ 1      │ 1           │
│ 95  │ 2008  │ 65000         │ 110000    │ 1      │ 1           │
│ 96  │ 2008  │ 65000         │ 140000    │ 1      │ 1           │
│ 97  │ 2011  │ 65000         │ 60000     │ 1      │ 1           │
│ 98  │ 2001  │ 68000         │ 70000     │ 1      │ 1           │
│ 99  │ 2001  │ 68000         │ 70000     │ 1      │ 1           │
│ 100 │ 2009  │ 68000         │ 120000    │ 1      │ 1           │

In [57]:
#Cek korelasi antar masing-masing kolom dengan "selling_price"

#Cek korelasi antara "year" dan "selling_price"
yearToSP = correlation(train[:,1], train[:,2])
print("Korelasi antara 'selling_price' dan 'year' adalah: ")
println(yearToSP)

#Cek korelasi antara "km_driven" dan "selling_price"
kmToSP = correlation(train[:,3], train[:,2])
print("Korelasi antara 'selling_price' dan 'km_driven' adalah: ")
println(kmToSP)

#Cek korelasi antara "fuel" dan "selling_price"
fuelToSP = correlation(fuel, train[:,2])
print("Korelasi antara 'selling' dan 'fuel' adalah: ")
println(fuelToSP)

#Cek korelasi antara "seller_type" dan "selling_price"
sellerToSP = correlation(seller, train[:,2])
print("Korelasi antara 'selling_price' dan 'seller_type' adalah: ")
println(sellerToSP)

#Cek korelasi antara "transmission" dan "selling_price"
transmissionToSP = correlation(transmission, train[:,2])
print("Korelasi antara 'selling_price' dan 'transmission' adalah: ")
println(transmissionToSP)

#Cek korelasi antara "owner" dan "selling_price"
ownerToSP = correlation(owner, train[:,2])
print("Korelasi antara 'selling_price' dan 'owner' adalah: ")
println(ownerToSP)




Korelasi antara 'selling_price' dan 'year' adalah: 0.029105235534804343
Korelasi antara 'selling_price' dan 'km_driven' adalah: 0.2008191173453509
Korelasi antara 'selling' dan 'fuel' adalah: -0.03255490399743602
Korelasi antara 'selling_price' dan 'seller_type' adalah: -0.14390292916147115
Korelasi antara 'selling_price' dan 'transmission' adalah: NaN
Korelasi antara 'selling_price' dan 'owner' adalah: 0.02976706088621736


In [66]:
# Nilai NaN artinya korelasi antara kedua kolom adalah nol
# Dari hasil di atas kolom yang paling pantas untuk menjadi Independent variable
# adalah kolom 'year', kolom 'fuel', dan kolom 'owner'

# Membentuk matriks yang berisikan dependent variable
independent = zeros(Int64, 100, 3)
independent[:,1] = train[:,1]
independent[:,2] = fuel
independent[:,3] = owner
independent

100×3 Array{Int64,2}:
 2005  1  1
 2000  1  2
 2004  1  2
 2002  1  2
 2009  1  2
 2012  1  2
 2004  1  1
 1998  1  3
 1998  1  3
 2001  1  4
 2004  1  2
 2010  1  4
 2011  1  4
    ⋮     
 2002  1  1
 2002  1  1
 2005  1  1
 2005  1  1
 2005  1  2
 2006  1  1
 2008  1  2
 2008  1  4
 2011  1  1
 2001  1  4
 2001  1  4
 2009  1  1

In [86]:
#Dependent variabelnya adalah 'selling_price'
#arraynya adalah sebagai berikut
dependent = train[:,2]

100-element Array{Int64,1}:
 20000
 22000
 30000
 35000
 35000
 35000
 37500
 40000
 40000
 40000
 40000
 40000
 40000
     ⋮
 65000
 65000
 65000
 65000
 65000
 65000
 65000
 65000
 65000
 68000
 68000
 68000

In [88]:
include("test.jl")
#Kita akan mencari koefisien dari Multiple Linear Regressionnya
b = findRegConstant(independent, dependent)

4×1 Array{Float64,2}:
 -71217.2038078187
     62.317769035868736
   -588.7271809647807
    220.6474457495957

In [90]:
# Persamaan Multiple Linear Regressionnya adalah
printRegression(b)

y = -71217.2038078187+ (62.317769035868736)x1+ (-588.7271809647807)x2+ (220.6474457495957)x3

In [101]:
using Plots

In [103]:
# Mengambil data test
test = sorted[101:150, :]
test

100×7 DataFrame. Omitted printing of 2 columns
│ Row │ year  │ selling_price │ km_driven │ fuel   │ seller_type │
│     │ Int64 │ Int64         │ Int64     │ String │ String      │
├─────┼───────┼───────────────┼───────────┼────────┼─────────────┤
│ 1   │ 2009  │ 68000         │ 120000    │ Petrol │ Individual  │
│ 2   │ 1998  │ 69000         │ 70000     │ Petrol │ Individual  │
│ 3   │ 2008  │ 69000         │ 100000    │ Petrol │ Individual  │
│ 4   │ 2008  │ 69000         │ 100000    │ Petrol │ Individual  │
│ 5   │ 1999  │ 70000         │ 70000     │ Petrol │ Individual  │
│ 6   │ 1999  │ 70000         │ 70000     │ Petrol │ Individual  │
│ 7   │ 2001  │ 70000         │ 117000    │ Petrol │ Individual  │
│ 8   │ 2001  │ 70000         │ 117000    │ Petrol │ Individual  │
│ 9   │ 2003  │ 70000         │ 60000     │ Petrol │ Individual  │
│ 10  │ 2003  │ 70000         │ 80000     │ Petrol │ Individual  │
⋮
│ 90  │ 2004  │ 80000         │ 120000    │ Petrol │ Individual  │
│ 91  │ 2005  │ 80000         │ 24000     │ Petrol │ Individual  │
│ 92  │ 2005  │ 80000         │ 40000     │ Petrol │ Individual  │
│ 93  │ 2005  │ 80000         │ 40000     │ Petrol │ Individual  │
│ 94  │ 2005  │ 80000         │ 56580     │ Petrol │ Dealer      │
│ 95  │ 2005  │ 80000         │ 56580     │ Petrol │ Dealer      │
│ 96  │ 2005  │ 80000         │ 56580     │ Petrol │ Dealer      │
│ 97  │ 2005  │ 80000         │ 56580     │ Petrol │ Dealer      │
│ 98  │ 2005  │ 80000         │ 56580     │ Petrol │ Dealer      │
│ 99  │ 2005  │ 80000         │ 56580     │ Petrol │ Dealer      │
│ 100 │ 2005  │ 80000         │ 56580     │ Petrol │ Dealer      │

In [107]:
# Plot tahun terhadap selling price
using .LinReg
using LinearAlgebra
#penghitungan result
result = zeros(50,1)
features = test[1:50,1:size(test,2)-1]
labels = test[1:50,size(test,2)]

for i in 1:30
    result[i,1] = dot(features[i,:],Regressor.weight)
end

factor1 = ones(50)
year = test[1:50,1]
yp = [factor1 year]
coYear = yp\result
f1 = coYear[1]*factor1 + coYear[2]*year

graf1 = scatter(year, labels, color=:green, label="Actual", xlabel="year", ylabel="selling_price", title="Hubungan year dan selling_price")
graf1 = plot!(year, f1, linewidth=1, color=:red, label = "Prediction")
plot(graf1)


UndefVarError: UndefVarError: Regressor not defined

In [ ]:
#Plot fuel terhadap selling_price
factor1 = ones(50)
fuel = test[1:50,4]
yp = [factor1 fuel]
coYear = yp\result
f1 = coYear[1]*factor1 + coYear[2]*fuel_type

graf2 = scatter(fuel, labels, color=:green, label="Actual", xlabel="fuel", ylabel="selling_price", title="Hubungan fuel dan selling_price")
graf2 = plot!(fuel, f1, linewidth=1, color=:red, label = "Prediction")

plot(graf2)

In [105]:
#Plot owner terhadap selling_price
factor1 = ones(50)
fuel = test[1:50,7]
yp = [factor1 fuel]
coYear = yp\result
f1 = coYear[1]*factor1 + coYear[2]*fuel_type

graf3 = scatter(fuel, labels, color=:green, label="Actual", xlabel="owner", ylabel="selling_price", title="Hubungan owner dan selling_price")
graf3 = plot!(fuel, f1, linewidth=1, color=:red, label = "Prediction")

plot(graf3)

UndefVarError: UndefVarError: result not defined